name: Trigger iCR

on:
  push:
    branches: [ '**' ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Use the latest version

    - name: Print current working directory
      run: pwd
      shell: bash
    - name: Print current working directory
      run: echo $pwd
      shell: bash

    - name: Print current working directory
      run: echo ${{ github.workspace }}
      shell: bash
    

