name: Trigger iCR

on:
  push:
    branches: [ '**' ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  

    - name: Download executable from Google Drive
      run: |
        curl -L -o icr_cli "https://docs.google.com/uc?export=download&id=1GeSv2Z1D_vgNUJ_gbI9CU92VeAwR_ilR"

    - name: Make the script executable
      run: |
        chmod +x icr_cli

    - name: Create a temporary directory to store results
      run: |
        mkdir /tmp/icr-results
    
    - name: Run icr engine
      run: |
       ./icr_cli -source ${{ github.workspace }} -result /tmp/icr-results -language java -license H8LW-V566-APNJ-TFOR -short
      shell: bash
      
    - name: Store the results
      uses: actions/upload-artifact@v4
      with:
        name: icr_results
        path: /tmp/icr-results
