name: Trigger iCR

on:
  push:
    branches: [ '**' ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Use the latest version

    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v1  # Optional if needed for building other images

    - name: Pull icr image
      run: |
        docker pull openrefactory/icr-java-engine:4.2.0

    - name: Print current working directory
        run: pwd
        shell: bash

    - name: List files in the current directory
      run: ls -la
      shell: bash
