name: Trigger iCR

on:
  push:
    branches: [ '**' ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Use the latest version

    - name: Pull icr image
      run: |
        docker pull openrefactory/icr-java-engine:4.2.0

    - name: Run static analysis tool with environment variable
      run: |
        docker run --rm \
            --env LICENSE_KEY=afsdfasdffds \
            --mount type=bind,source=${{ github.workspace }},target=/workspace/source \
            openrefactory/icr-java-engine:4.2.0 /bin/bash -c "
              echo 'Checking /workspace/source';
              ls -la /workspace/source;
              file /workspace/source"
    

