name: Trigger iCR

on:
  push:
    branches: [ '**' ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Use the latest version

    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v1  # Optional if needed for building other images

    - name: Pull icr image
      run: |
        docker pull openrefactory/icr-java-engine:4.2.0

    - name: Run static analysis tool with environment variable
      run: |
        docker run --env LICENSE_KEY=H8LW-V566-APNJ-TFO \
           openrefactory/icr-java-engine:4.2.0 \
          --mount type=bind,source=${{ github.workspace }},target=/workspace/source \
          --mount type=bind,source=${{ github.workspace }},target=/workspace/result \

